// 中学受験タイピングアプリ - 問題データ (Part 3 - 新規カテゴリ)

const categories_part3 = [
  {
    id: 'math',
    name: '算数用語',
    icon: '🔢',
    description: '算数・数学の重要用語',
    words: [
      { word: '分数', reading: 'ぶんすう', hint: '分母と分子' },
      { word: '小数', reading: 'しょうすう', hint: '小数点' },
      { word: '整数', reading: 'せいすう', hint: 'プラスマイナスの数' },
      { word: '約数', reading: 'やくすう', hint: '割り切れる数' },
      { word: '倍数', reading: 'ばいすう', hint: '掛け算の答え' },
      { word: '素数', reading: 'そすう', hint: '1とその数でしか割れない' },
      { word: '公倍数', reading: 'こうばいすう', hint: '共通の倍数' },
      { word: '公約数', reading: 'こうやくすう', hint: '共通の約数' },
      { word: '最小公倍数', reading: 'さいしょうこうばいすう', hint: '一番小さい公倍数' },
      { word: '最大公約数', reading: 'さいだいこうやくすう', hint: '一番大きい公約数' },
      { word: '平行四辺形', reading: 'へいこうしへんけい', hint: '向かい合う辺が平行' },
      { word: '台形', reading: 'だいけい', hint: '1組だけ平行' },
      { word: 'ひし形', reading: 'ひしがた', hint: '4つの辺が等しい' },
      { word: '正方形', reading: 'せいほうけい', hint: '4つの角が直角で辺が等しい' },
      { word: '長方形', reading: 'ちょうほうけい', hint: '4つの角が直角' },
      { word: '三角形', reading: 'さんかくけい', hint: '3つの辺' },
      { word: '二等辺三角形', reading: 'にとうへんさんかくけい', hint: '2つの辺が等しい' },
      { word: '正三角形', reading: 'せいさんかくけい', hint: '3つの辺が等しい' },
      { word: '直角三角形', reading: 'ちょっかくさんかくけい', hint: '1つの角が直角' },
      { word: '円周率', reading: 'えんしゅうりつ', hint: '3.14' },
      { word: '直径', reading: 'ちょっけい', hint: '円の中心を通る線' },
      { word: '半径', reading: 'はんけい', hint: '中心から円周まで' },
      { word: '面積', reading: 'めんせき', hint: '広さ' },
      { word: '体積', reading: 'たいせき', hint: 'かさ' },
      { word: '周の長さ', reading: 'しゅうのながさ', hint: '周りの長さ' },
      { word: '角度', reading: 'かくど', hint: '度で表す' },
      { word: '垂直', reading: 'すいちょく', hint: '直角に交わる' },
      { word: '平行', reading: 'へいこう', hint: '交わらない' },
      { word: '対称', reading: 'たいしょう', hint: '線対称・点対称' },
      { word: '合同', reading: 'ごうどう', hint: 'ぴったり重なる' }
    ]
  },
  {
    id: 'country',
    name: '世界の国々',
    icon: '🌍',
    description: '世界の主要な国名',
    words: [
      { word: 'アメリカ合衆国', reading: 'あめりかがっしゅうこく', hint: '北米の大国' },
      { word: 'イギリス', reading: 'いぎりす', hint: 'ヨーロッパの島国' },
      { word: 'フランス', reading: 'ふらんす', hint: 'エッフェル塔' },
      { word: 'ドイツ', reading: 'どいつ', hint: 'ヨーロッパの中心' },
      { word: 'イタリア', reading: 'いたりあ', hint: '長靴の形' },
      { word: 'スペイン', reading: 'すぺいん', hint: 'イベリア半島' },
      { word: 'ロシア', reading: 'ろしあ', hint: '世界最大の国土' },
      { word: '中国', reading: 'ちゅうごく', hint: '人口世界一' },
      { word: '韓国', reading: 'かんこく', hint: '朝鮮半島南部' },
      { word: '北朝鮮', reading: 'きたちょうせん', hint: '朝鮮半島北部' },
      { word: 'インド', reading: 'いんど', hint: '南アジアの大国' },
      { word: 'タイ', reading: 'たい', hint: '東南アジア' },
      { word: 'ベトナム', reading: 'べとなむ', hint: 'インドシナ半島' },
      { word: 'フィリピン', reading: 'ふぃりぴん', hint: '島国' },
      { word: 'インドネシア', reading: 'いんどねしあ', hint: '赤道直下の島国' },
      { word: 'マレーシア', reading: 'まれーしあ', hint: 'マレー半島' },
      { word: 'シンガポール', reading: 'しんがぽーる', hint: '都市国家' },
      { word: 'オーストラリア', reading: 'おーすとらりあ', hint: 'オセアニア大陸' },
      { word: 'ニュージーランド', reading: 'にゅーじーらんど', hint: '羊の国' },
      { word: 'カナダ', reading: 'かなだ', hint: '北米の大国' },
      { word: 'メキシコ', reading: 'めきしこ', hint: '中米' },
      { word: 'ブラジル', reading: 'ぶらじる', hint: '南米最大' },
      { word: 'アルゼンチン', reading: 'あるぜんちん', hint: '南米南部' },
      { word: 'エジプト', reading: 'えじぷと', hint: 'ピラミッド' },
      { word: '南アフリカ', reading: 'みなみあふりか', hint: 'アフリカ南端' },
      { word: 'トルコ', reading: 'とるこ', hint: 'アジアとヨーロッパ' },
      { word: 'サウジアラビア', reading: 'さうじあらびあ', hint: '中東の大国' },
      { word: 'イスラエル', reading: 'いすらえる', hint: '中東' },
      { word: 'ギリシャ', reading: 'ぎりしゃ', hint: '古代文明' },
      { word: 'スイス', reading: 'すいす', hint: 'アルプス' }
    ]
  },
  {
    id: 'scientist',
    name: '世界の偉人',
    icon: '🎓',
    description: '歴史に名を残した偉人たち',
    words: [
      { word: 'ニュートン', reading: 'にゅーとん', hint: 'りんごと万有引力' },
      { word: 'エジソン', reading: 'えじそん', hint: '発明王' },
      { word: 'アインシュタイン', reading: 'あいんしゅたいん', hint: '相対性理論' },
      { word: 'ガリレオ', reading: 'がりれお', hint: '地動説' },
      { word: 'コペルニクス', reading: 'こぺるにくす', hint: '地動説' },
      { word: 'ダーウィン', reading: 'だーうぃん', hint: '進化論' },
      { word: 'キュリー夫人', reading: 'きゅりーふじん', hint: 'ラジウム発見' },
      { word: 'パスツール', reading: 'ぱすつーる', hint: '微生物学' },
      { word: 'ベートーベン', reading: 'べーとーべん', hint: '音楽家' },
      { word: 'モーツァルト', reading: 'もーつぁると', hint: '天才音楽家' },
      { word: 'ピカソ', reading: 'ぴかそ', hint: '画家' },
      { word: 'ゴッホ', reading: 'ごっほ', hint: 'ひまわり' },
      { word: 'レオナルドダビンチ', reading: 'れおなるどだびんち', hint: 'モナリザ' },
      { word: 'シェイクスピア', reading: 'しぇいくすぴあ', hint: '劇作家' },
      { word: 'ナポレオン', reading: 'なぽれおん', hint: 'フランス皇帝' },
      { word: 'リンカーン', reading: 'りんかーん', hint: 'アメリカ大統領' },
      { word: 'ワシントン', reading: 'わしんとん', hint: '初代大統領' },
      { word: 'ガンジー', reading: 'がんじー', hint: 'インド独立' },
      { word: 'マザーテレサ', reading: 'まざーてれさ', hint: '慈善活動' },
      { word: 'コロンブス', reading: 'ころんぶす', hint: 'アメリカ大陸発見' },
      { word: 'マゼラン', reading: 'まぜらん', hint: '世界一周' },
      { word: 'ライト兄弟', reading: 'らいときょうだい', hint: '飛行機' },
      { word: 'ベル', reading: 'べる', hint: '電話の発明' },
      { word: 'グーテンベルク', reading: 'ぐーてんべるく', hint: '印刷術' },
      { word: 'ノーベル', reading: 'のーべる', hint: 'ノーベル賞' },
      { word: 'アルキメデス', reading: 'あるきめです', hint: '古代ギリシャの科学者' },
      { word: 'ソクラテス', reading: 'そくらてす', hint: '哲学者' },
      { word: 'プラトン', reading: 'ぷらとん', hint: '哲学者' },
      { word: 'アリストテレス', reading: 'ありすとてれす', hint: '哲学者' },
      { word: 'ピタゴラス', reading: 'ぴたごらす', hint: '数学者' }
    ]
  },
  {
    id: 'mountain',
    name: '日本の山',
    icon: '⛰️',
    description: '日本の有名な山々',
    words: [
      { word: '富士山', reading: 'ふじさん', hint: '日本最高峰3776m' },
      { word: '北岳', reading: 'きただけ', hint: '南アルプス' },
      { word: '穂高岳', reading: 'ほたかだけ', hint: '北アルプス' },
      { word: '槍ヶ岳', reading: 'やりがたけ', hint: '日本のマッターホルン' },
      { word: '剱岳', reading: 'つるぎだけ', hint: '北アルプス' },
      { word: '立山', reading: 'たてやま', hint: '北アルプス' },
      { word: '白馬岳', reading: 'しろうまだけ', hint: '北アルプス' },
      { word: '八ヶ岳', reading: 'やつがたけ', hint: '中部地方' },
      { word: '甲斐駒ヶ岳', reading: 'かいこまがたけ', hint: '南アルプス' },
      { word: '仙丈ヶ岳', reading: 'せんじょうがたけ', hint: '南アルプス' },
      { word: '乗鞍岳', reading: 'のりくらだけ', hint: '北アルプス' },
      { word: '御嶽山', reading: 'おんたけさん', hint: '中央アルプス' },
      { word: '木曽駒ヶ岳', reading: 'きそこまがたけ', hint: '中央アルプス' },
      { word: '赤石岳', reading: 'あかいしだけ', hint: '南アルプス' },
      { word: '荒川岳', reading: 'あらかわだけ', hint: '南アルプス' },
      { word: '浅間山', reading: 'あさまやま', hint: '活火山' },
      { word: '那須岳', reading: 'なすだけ', hint: '栃木県' },
      { word: '日光白根山', reading: 'にっこうしらねさん', hint: '栃木県' },
      { word: '筑波山', reading: 'つくばさん', hint: '茨城県' },
      { word: '谷川岳', reading: 'たにがわだけ', hint: '群馬県' },
      { word: '妙高山', reading: 'みょうこうさん', hint: '新潟県' },
      { word: '月山', reading: 'がっさん', hint: '山形県' },
      { word: '鳥海山', reading: 'ちょうかいさん', hint: '秋田・山形' },
      { word: '岩木山', reading: 'いわきさん', hint: '青森県' },
      { word: '岩手山', reading: 'いわてさん', hint: '岩手県' },
      { word: '蔵王山', reading: 'ざおうさん', hint: '山形・宮城' },
      { word: '阿蘇山', reading: 'あそさん', hint: '熊本県' },
      { word: '桜島', reading: 'さくらじま', hint: '鹿児島県' },
      { word: '雲仙岳', reading: 'うんぜんだけ', hint: '長崎県' },
      { word: '大山', reading: 'だいせん', hint: '鳥取県' }
    ]
  },
  {
    id: 'idiom',
    name: '慣用句',
    icon: '💬',
    description: 'よく使われる慣用句',
    words: [
      { word: '足を洗う', reading: 'あしをあらう', hint: '悪い生活をやめる' },
      { word: '頭が上がらない', reading: 'あたまがあがらない', hint: '恩義がある' },
      { word: '息が合う', reading: 'いきがあう', hint: '調子が合う' },
      { word: '肩を持つ', reading: 'かたをもつ', hint: '味方する' },
      { word: '口が軽い', reading: 'くちがかるい', hint: 'すぐ喋る' },
      { word: '口が堅い', reading: 'くちがかたい', hint: '秘密を守る' },
      { word: '首を長くする', reading: 'くびをながくする', hint: '待ち遠しい' },
      { word: '首を突っ込む', reading: 'くびをつっこむ', hint: '関わる' },
      { word: '腰が低い', reading: 'こしがひくい', hint: '謙虚' },
      { word: '腰を折る', reading: 'こしをおる', hint: '話を中断する' },
      { word: '後ろ髪を引かれる', reading: 'うしろがみをひかれる', hint: '名残惜しい' },
      { word: '目が高い', reading: 'めがたかい', hint: '鑑識眼がある' },
      { word: '目を白黒させる', reading: 'めをしろくろさせる', hint: '驚く' },
      { word: '耳が痛い', reading: 'みみがいたい', hint: '聞くのがつらい' },
      { word: '耳を疑う', reading: 'みみをうたがう', hint: '信じられない' },
      { word: '鼻が高い', reading: 'はながたかい', hint: '誇らしい' },
      { word: '鼻で笑う', reading: 'はなでわらう', hint: 'バカにする' },
      { word: '手を焼く', reading: 'てをやく', hint: '扱いに困る' },
      { word: '手を打つ', reading: 'てをうつ', hint: '対策する' },
      { word: '腹が黒い', reading: 'はらがくろい', hint: '悪だくみする' },
      { word: '腹を割る', reading: 'はらをわる', hint: '本音を話す' },
      { word: '胸を張る', reading: 'むねをはる', hint: '堂々とする' },
      { word: '胸が痛む', reading: 'むねがいたむ', hint: '心配する' },
      { word: '顔が広い', reading: 'かおがひろい', hint: '知り合いが多い' },
      { word: '顔から火が出る', reading: 'かおからひがでる', hint: '恥ずかしい' },
      { word: '歯が立たない', reading: 'はがたたない', hint: 'かなわない' },
      { word: '歯に衣着せぬ', reading: 'はにきぬきせぬ', hint: '遠慮なく言う' },
      { word: '舌を巻く', reading: 'したをまく', hint: '驚嘆する' },
      { word: '喉から手が出る', reading: 'のどからてがでる', hint: '欲しくてたまらない' },
      { word: '二の足を踏む', reading: 'にのあしをふむ', hint: 'ためらう' }
    ]
  }
];

// カテゴリを統合
const categories = [...categories_part1, ...categories_part2, ...categories_part3];
