// 中学受験タイピングアプリ - 問題データ (Part 2)

const categories_part2 = [
  {
    id: 'writer',
    name: '文豪',
    icon: '📚',
    description: '日本の有名な作家たち',
    words: [
      { word: '夏目漱石', reading: 'なつめそうせき', hint: '吾輩は猫である' },
      { word: '芥川龍之介', reading: 'あくたがわりゅうのすけ', hint: '羅生門' },
      { word: '太宰治', reading: 'だざいおさむ', hint: '人間失格' },
      { word: '川端康成', reading: 'かわばたやすなり', hint: '雪国' },
      { word: '三島由紀夫', reading: 'みしまゆきお', hint: '金閣寺' },
      { word: '谷崎潤一郎', reading: 'たにざきじゅんいちろう', hint: '細雪' },
      { word: '志賀直哉', reading: 'しがなおや', hint: '暗夜行路' },
      { word: '森鴎外', reading: 'もりおうがい', hint: '舞姫' },
      { word: '樋口一葉', reading: 'ひぐちいちよう', hint: 'たけくらべ' },
      { word: '与謝野晶子', reading: 'よさのあきこ', hint: 'みだれ髪' },
      { word: '石川啄木', reading: 'いしかわたくぼく', hint: '一握の砂' },
      { word: '宮沢賢治', reading: 'みやざわけんじ', hint: '銀河鉄道の夜' },
      { word: '島崎藤村', reading: 'しまざきとうそん', hint: '破戒' },
      { word: '正岡子規', reading: 'まさおかしき', hint: '俳句革新' },
      { word: '井原西鶴', reading: 'いはらさいかく', hint: '好色一代男' },
      { word: '松尾芭蕉', reading: 'まつおばしょう', hint: '奥の細道' },
      { word: '小林一茶', reading: 'こばやしいっさ', hint: 'おらが春' },
      { word: '与謝蕪村', reading: 'よさぶそん', hint: '俳諧' },
      { word: '紀貫之', reading: 'きのつらゆき', hint: '土佐日記' },
      { word: '清少納言', reading: 'せいしょうなごん', hint: '枕草子' },
      { word: '紫式部', reading: 'むらさきしきぶ', hint: '源氏物語' },
      { word: '吉田兼好', reading: 'よしだけんこう', hint: '徒然草' },
      { word: '鴨長明', reading: 'かものちょうめい', hint: '方丈記' },
      { word: '二葉亭四迷', reading: 'ふたばていしめい', hint: '浮雲' },
      { word: '坪内逍遥', reading: 'つぼうちしょうよう', hint: '小説神髄' },
      { word: '尾崎紅葉', reading: 'おざきこうよう', hint: '金色夜叉' },
      { word: '幸田露伴', reading: 'こうだろはん', hint: '五重塔' },
      { word: '国木田独歩', reading: 'くにきだどっぽ', hint: '武蔵野' },
      { word: '田山花袋', reading: 'たやまかたい', hint: '蒲団' },
      { word: '有島武郎', reading: 'ありしまたけお', hint: 'カインの末裔' },
      { word: '武者小路実篤', reading: 'むしゃこうじさねあつ', hint: '友情' },
      { word: '菊池寛', reading: 'きくちかん', hint: '恩讐の彼方に' },
      { word: '江戸川乱歩', reading: 'えどがわらんぽ', hint: '怪人二十面相' },
      { word: '横光利一', reading: 'よこみつりいち', hint: '機械' },
      { word: '中島敦', reading: 'なかじまあつし', hint: '山月記' },
      { word: '坂口安吾', reading: 'さかぐちあんご', hint: '堕落論' },
      { word: '井伏鱒二', reading: 'いぶせますじ', hint: '黒い雨' },
      { word: '堀辰雄', reading: 'ほりたつお', hint: '風立ちぬ' },
      { word: '永井荷風', reading: 'ながいかふう', hint: '濹東綺譚' },
      { word: '梶井基次郎', reading: 'かじいもとじろう', hint: '檸檬' }
    ]
  },
  {
    id: 'constellation',
    name: '星座',
    icon: '⭐',
    description: '十二星座と有名な星座',
    words: [
      { word: 'おひつじ座', reading: 'おひつじざ', hint: '3月21日〜4月19日' },
      { word: 'おうし座', reading: 'おうしざ', hint: '4月20日〜5月20日' },
      { word: 'ふたご座', reading: 'ふたござ', hint: '5月21日〜6月21日' },
      { word: 'かに座', reading: 'かにざ', hint: '6月22日〜7月22日' },
      { word: 'しし座', reading: 'ししざ', hint: '7月23日〜8月22日' },
      { word: 'おとめ座', reading: 'おとめざ', hint: '8月23日〜9月22日' },
      { word: 'てんびん座', reading: 'てんびんざ', hint: '9月23日〜10月23日' },
      { word: 'さそり座', reading: 'さそりざ', hint: '10月24日〜11月21日' },
      { word: 'いて座', reading: 'いてざ', hint: '11月22日〜12月21日' },
      { word: 'やぎ座', reading: 'やぎざ', hint: '12月22日〜1月19日' },
      { word: 'みずがめ座', reading: 'みずがめざ', hint: '1月20日〜2月18日' },
      { word: 'うお座', reading: 'うおざ', hint: '2月19日〜3月20日' },
      { word: 'オリオン座', reading: 'おりおんざ', hint: '冬の代表的な星座' },
      { word: 'カシオペヤ座', reading: 'かしおぺやざ', hint: 'Wの形' },
      { word: 'おおぐま座', reading: 'おおぐまざ', hint: '北斗七星' },
      { word: 'こぐま座', reading: 'こぐまざ', hint: '北極星' },
      { word: 'はくちょう座', reading: 'はくちょうざ', hint: '夏の大三角' },
      { word: 'わし座', reading: 'わしざ', hint: 'アルタイル' },
      { word: 'こと座', reading: 'こ���ざ', hint: 'ベガ' },
      { word: 'アンドロメダ座', reading: 'あんどろめだざ', hint: '王女の星座' },
      { word: 'ペルセウス座', reading: 'ぺるせうすざ', hint: '勇者の星座' },
      { word: 'ケンタウルス座', reading: 'けんたうるすざ', hint: '南半球' },
      { word: 'りゅう座', reading: 'りゅうざ', hint: '北天' },
      { word: 'ヘルクレス座', reading: 'へるくれすざ', hint: '英雄' },
      { word: 'ペガスス座', reading: 'ぺがすすざ', hint: '天馬' },
      { word: 'おおいぬ座', reading: 'おおいぬざ', hint: 'シリウス' },
      { word: 'こいぬ座', reading: 'こいぬざ', hint: 'プロキオン' },
      { word: 'うさぎ座', reading: 'うさぎざ', hint: 'オリオンの下' },
      { word: 'エリダヌス座', reading: 'えりだぬすざ', hint: '長い川' },
      { word: 'くじら座', reading: 'くじらざ', hint: '秋の星座' }
    ]
  },
  {
    id: 'history',
    name: '歴史人物',
    icon: '👤',
    description: '日本史の重要人物',
    words: [
      { word: '聖徳太子', reading: 'しょうとくたいし', hint: '十七条の憲法' },
      { word: '中大兄皇子', reading: 'なかのおおえのおうじ', hint: '大化の改新' },
      { word: '中臣鎌足', reading: 'なかとみのかまたり', hint: '藤原氏の祖' },
      { word: '聖武天皇', reading: 'しょうむてんのう', hint: '東大寺大仏' },
      { word: '行基', reading: 'ぎょうき', hint: '奈良時代の僧' },
      { word: '鑑真', reading: 'がんじん', hint: '唐招提寺' },
      { word: '藤原道長', reading: 'ふじわらのみちなが', hint: '摂関政治' },
      { word: '平清盛', reading: 'たいらのきよもり', hint: '平氏政権' },
      { word: '源義経', reading: 'みなもとのよしつね', hint: '悲劇の武将' },
      { word: '源頼朝', reading: 'みなもとのよりとも', hint: '鎌倉幕府' },
      { word: '北条時政', reading: 'ほうじょうときまさ', hint: '執権政治' },
      { word: '北条政子', reading: 'ほうじょうまさこ', hint: '尼将軍' },
      { word: '北条泰時', reading: 'ほうじょうやすとき', hint: '御成敗式目' },
      { word: '後醍醐天皇', reading: 'ごだいごてんのう', hint: '建武の新政' },
      { word: '足利尊氏', reading: 'あしかがたかうじ', hint: '室町幕府' },
      { word: '足利義満', reading: 'あしかがよしみつ', hint: '金閣寺' },
      { word: '足利義政', reading: 'あしかがよしまさ', hint: '銀閣寺' },
      { word: '新田義貞', reading: 'にったよしさだ', hint: '鎌倉攻め' },
      { word: '楠木正成', reading: 'くすのきまさしげ', hint: '忠臣' },
      { word: 'ザビエル', reading: 'ざびえる', hint: 'キリスト教伝来' },
      { word: '千利休', reading: 'せんのりきゅう', hint: '茶道' },
      { word: '狩野永徳', reading: 'かのうえいとく', hint: '画家' },
      { word: '出雲阿国', reading: 'いずものおくに', hint: '歌舞伎' },
      { word: '近松門左衛門', reading: 'ちかまつもんざえもん', hint: '人形浄瑠璃' },
      { word: '本居宣長', reading: 'もとおりのりなが', hint: '古事記伝' },
      { word: '杉田玄白', reading: 'すぎたげんぱく', hint: '解体新書' },
      { word: '伊能忠敬', reading: 'いのうただたか', hint: '日本地図' },
      { word: 'ペリー', reading: 'ぺりー', hint: '黒船来航' },
      { word: '坂本龍馬', reading: 'さかもとりょうま', hint: '海援隊' },
      { word: '西郷隆盛', reading: 'さいごうたかもり', hint: '維新三傑' },
      { word: '大久保利通', reading: 'おおくぼとしみち', hint: '維新三傑' },
      { word: '木戸孝允', reading: 'きどたかよし', hint: '維新三傑' },
      { word: '勝海舟', reading: 'かつかいしゅう', hint: '江戸無血開城' },
      { word: '吉田松陰', reading: 'よしだしょういん', hint: '松下村塾' },
      { word: '高杉晋作', reading: 'たかすぎしんさく', hint: '奇兵隊' },
      { word: '伊藤博文', reading: 'いとうひろぶみ', hint: '初代内閣総理大臣' },
      { word: '板垣退助', reading: 'いたがきたいすけ', hint: '自由民権運動' },
      { word: '大隈重信', reading: 'おおくましげのぶ', hint: '早稲田大学創立' },
      { word: '福沢諭吉', reading: 'ふくざわゆきち', hint: '学問のすすめ' },
      { word: '渋沢栄一', reading: 'しぶさわえいいち', hint: '日本資本主義の父' },
      { word: '野口英世', reading: 'のぐちひでよ', hint: '細菌学者' },
      { word: '北里柴三郎', reading: 'きたさとしばさぶろう', hint: '破傷風血清' }
    ]
  },
  {
    id: 'yojijukugo',
    name: '四字熟語',
    icon: '📝',
    description: '中学受験でよく出る四字熟語',
    words: [
      { word: '一期一会', reading: 'いちごいちえ', hint: '生涯に一度の出会い' },
      { word: '以心伝心', reading: 'いしんでんしん', hint: '心が通じ合う' },
      { word: '温故知新', reading: 'おんこちしん', hint: '古きを知り新しきを知る' },
      { word: '切磋琢磨', reading: 'せっさたくま', hint: '互いに励まし合う' },
      { word: '一石二鳥', reading: 'いっせきにちょう', hint: '一つで二つの利益' },
      { word: '弱肉強食', reading: 'じゃくにくきょうしょく', hint: '強いものが勝つ' },
      { word: '七転八倒', reading: 'しちてんばっとう', hint: '激しく苦しむ' },
      { word: '四面楚歌', reading: 'しめんそか', hint: '周りが敵だらけ' },
      { word: '自画自賛', reading: 'じがじさん', hint: '自分で褒める' },
      { word: '百花繚乱', reading: 'ひゃっかりょうらん', hint: '美しく咲き誇る' },
      { word: '馬耳東風', reading: 'ばじとうふう', hint: '聞いても聞き流す' },
      { word: '油断大敵', reading: 'ゆだんたいてき', hint: '油断は禁物' },
      { word: '竜頭蛇尾', reading: 'りゅうとうだび', hint: '初めだけ立派' },
      { word: '一攫千金', reading: 'いっかくせんきん', hint: '一度に大金を得る' },
      { word: '異口同音', reading: 'いくどうおん', hint: '皆同じことを言う' },
      { word: '因果応報', reading: 'いんがおうほう', hint: '良い悪いが返ってくる' },
      { word: '千差万別', reading: 'せんさばんべつ', hint: '様々な違い' },
      { word: '前人未踏', reading: 'ぜんじんみとう', hint: '誰も達成していない' },
      { word: '大器晩成', reading: 'たいきばんせい', hint: '遅咲きの才能' },
      { word: '朝令暮改', reading: 'ちょうれいぼかい', hint: '方針が変わりやすい' },
      { word: '同床異夢', reading: 'どうしょういむ', hint: '同じ場所で違う夢' },
      { word: '日進月歩', reading: 'にっしんげっぽ', hint: '絶え間なく進歩' },
      { word: '波瀾万丈', reading: 'はらんばんじょう', hint: '変化に富んだ人生' },
      { word: '針小棒大', reading: 'しんしょうぼうだい', hint: '大げさに言う' },
      { word: '臨機応変', reading: 'りんきおうへん', hint: '状況に応じて対応' },
      { word: '試行錯誤', reading: 'しこうさくご', hint: '失敗を繰り返して学ぶ' },
      { word: '一心不乱', reading: 'いっしんふらん', hint: '一つのことに集中' },
      { word: '絶体絶命', reading: 'ぜったいぜつめい', hint: '逃げ場のない状態' },
      { word: '天変地異', reading: 'てんぺんちい', hint: '大きな自然災害' },
      { word: '無我夢中', reading: 'むがむちゅう', hint: '我を忘れて没頭' },
      { word: '有名無実', reading: 'ゆうめいむじつ', hint: '名ばかりで実がない' },
      { word: '起承転結', reading: 'きしょうてんけつ', hint: '文章の構成' },
      { word: '言語道断', reading: 'ごんごどうだん', hint: 'もってのほか' },
      { word: '五里霧中', reading: 'ごりむちゅう', hint: '方向がわからない' },
      { word: '支離滅裂', reading: 'しりめつれつ', hint: 'まとまりがない' },
      { word: '紆余曲折', reading: 'うよきょくせつ', hint: '曲がりくねった経過' },
      { word: '誠心誠意', reading: 'せいしんせいい', hint: '真心を込めて' },
      { word: '喜怒哀楽', reading: 'きどあいらく', hint: '感情の変化' },
      { word: '天真爛漫', reading: 'てんしんらんまん', hint: '無邪気で明るい' },
      { word: '質実剛健', reading: 'しつじつごうけん', hint: '飾らず強い' }
    ]
  },
  {
    id: 'science',
    name: '理科用語',
    icon: '🔬',
    description: '理科で覚える重要用語',
    words: [
      { word: '光合成', reading: 'こうごうせい', hint: '植物が光で栄養を作る' },
      { word: '蒸発', reading: 'じょうはつ', hint: '液体が気体になる' },
      { word: '凝固', reading: 'ぎょうこ', hint: '液体が固体になる' },
      { word: '溶解', reading: 'ようかい', hint: '物質が液体に溶ける' },
      { word: '電流', reading: 'でんりゅう', hint: '電気の流れ' },
      { word: '磁石', reading: 'じしゃく', hint: 'N極とS極' },
      { word: '天体', reading: 'てんたい', hint: '宇宙の星や惑星' },
      { word: '地層', reading: 'ちそう', hint: '地面の層' },
      { word: '化石', reading: 'かせき', hint: '大昔の生物の痕跡' },
      { word: '火山', reading: 'かざん', hint: 'マグマが噴出' },
      { word: '地震', reading: 'じしん', hint: '地面が揺れる' },
      { word: 'プランクトン', reading: 'ぷらんくとん', hint: '水中の微生物' },
      { word: '昆虫', reading: 'こんちゅう', hint: '頭・胸・腹' },
      { word: '脊椎動物', reading: 'せきついどうぶつ', hint: '背骨のある動物' },
      { word: '無脊椎動物', reading: 'むせきついどうぶつ', hint: '背骨のない動物' },
      { word: '被子植物', reading: 'ひししょくぶつ', hint: '花を咲かせる' },
      { word: '裸子植物', reading: 'らししょくぶつ', hint: 'マツやスギ' },
      { word: '双子葉類', reading: 'そうしようるい', hint: '子葉が二枚' },
      { word: '単子葉類', reading: 'たんしようるい', hint: '子葉が一枚' },
      { word: '気孔', reading: 'きこう', hint: '葉の呼吸口' },
      { word: '葉緑体', reading: 'ようりょくたい', hint: '光合成をする部分' },
      { word: '花粉', reading: 'かふん', hint: '花の受粉' },
      { word: '胚珠', reading: 'はいしゅ', hint: '種子になる部分' },
      { word: '果実', reading: 'かじつ', hint: '種子を包む' },
      { word: '発芽', reading: 'はつが', hint: '種から芽が出る' },
      { word: '根毛', reading: 'こんもう', hint: '根の細かい毛' },
      { word: '変態', reading: 'へんたい', hint: '形が変わる' },
      { word: '完全変態', reading: 'かんぜんへんたい', hint: 'サナギになる' },
      { word: '不完全変態', reading: 'ふかんぜんへんたい', hint: 'サナギにならない' },
      { word: '恒温動物', reading: 'こうおんどうぶつ', hint: '体温が一定' },
      { word: '変温動物', reading: 'へんおんどうぶつ', hint: '体温が変わる' },
      { word: '卵生', reading: 'らんせい', hint: '卵を産む' },
      { word: '胎生', reading: 'たいせい', hint: '子を産む' },
      { word: '冬眠', reading: 'とうみん', hint: '冬の間眠る' },
      { word: '擬態', reading: 'ぎたい', hint: '他の生物に似せる' },
      { word: '保護色', reading: 'ほごしょく', hint: '周りと同じ色' },
      { word: '食物連鎖', reading: 'しょくもつれんさ', hint: '食べる食べられるの関係' },
      { word: '生態系', reading: 'せいたいけい', hint: '生物と環境' },
      { word: '分解者', reading: 'ぶんかいしゃ', hint: '有機物を分解' },
      { word: '生産者', reading: 'せいさんしゃ', hint: '栄養を作る' }
    ]
  },
  {
    id: 'element',
    name: '元素記号',
    icon: '⚗️',
    description: '化学の元素記号',
    words: [
      { word: '水素', reading: 'すいそ', hint: 'H' },
      { word: 'ヘリウム', reading: 'へりうむ', hint: 'He' },
      { word: '炭素', reading: 'たんそ', hint: 'C' },
      { word: '窒素', reading: 'ちっそ', hint: 'N' },
      { word: '酸素', reading: 'さんそ', hint: 'O' },
      { word: 'ナトリウム', reading: 'なとりうむ', hint: 'Na' },
      { word: 'マグネシウム', reading: 'まぐねしうむ', hint: 'Mg' },
      { word: 'アルミニウム', reading: 'あるみにうむ', hint: 'Al' },
      { word: 'ケイ素', reading: 'けいそ', hint: 'Si' },
      { word: 'リン', reading: 'りん', hint: 'P' },
      { word: '硫黄', reading: 'いおう', hint: 'S' },
      { word: '塩素', reading: 'えんそ', hint: 'Cl' },
      { word: 'カリウム', reading: 'かりうむ', hint: 'K' },
      { word: 'カルシウム', reading: 'かるしうむ', hint: 'Ca' },
      { word: '鉄', reading: 'てつ', hint: 'Fe' },
      { word: '銅', reading: 'どう', hint: 'Cu' },
      { word: '亜鉛', reading: 'あえん', hint: 'Zn' },
      { word: '銀', reading: 'ぎん', hint: 'Ag' },
      { word: 'ヨウ素', reading: 'ようそ', hint: 'I' },
      { word: '金', reading: 'きん', hint: 'Au' },
      { word: '水銀', reading: 'すいぎん', hint: 'Hg' },
      { word: '鉛', reading: 'なまり', hint: 'Pb' },
      { word: 'ネオン', reading: 'ねおん', hint: 'Ne' },
      { word: 'アルゴン', reading: 'あるごん', hint: 'Ar' },
      { word: 'フッ素', reading: 'ふっそ', hint: 'F' },
      { word: 'ホウ素', reading: 'ほうそ', hint: 'B' },
      { word: 'クロム', reading: 'くろむ', hint: 'Cr' },
      { word: 'マンガン', reading: 'まんがん', hint: 'Mn' },
      { word: 'ニッケル', reading: 'にっける', hint: 'Ni' },
      { word: 'バリウム', reading: 'ばりうむ', hint: 'Ba' }
    ]
  },
  {
    id: 'heritage',
    name: '日本の世界遺産',
    icon: '🏯',
    description: '日本の世界遺産',
    words: [
      { word: '法隆寺', reading: 'ほうりゅうじ', hint: '奈良県' },
      { word: '姫路城', reading: 'ひめじじょう', hint: '兵庫県' },
      { word: '屋久島', reading: 'やくしま', hint: '鹿児島県' },
      { word: '白神山地', reading: 'しらかみさんち', hint: '青森・秋田' },
      { word: '古都京都', reading: 'ことkyoto', hint: '京都府' },
      { word: '白川郷', reading: 'しらかわごう', hint: '岐阜県' },
      { word: '原爆ドーム', reading: 'げんばくどーむ', hint: '広島県' },
      { word: '厳島神社', reading: 'いつくしまじんじゃ', hint: '広島県' },
      { word: '古都奈良', reading: 'ことなら', hint: '奈良県' },
      { word: '日光東照宮', reading: 'にっこうとうしょうぐう', hint: '栃木県' },
      { word: '琉球王国', reading: 'りゅうきゅうおうこく', hint: '沖縄県' },
      { word: '紀伊山地', reading: 'きいさんち', hint: '三重・奈良・和歌山' },
      { word: '知床', reading: 'しれとこ', hint: '北海道' },
      { word: '石見銀山', reading: 'いわみぎんざん', hint: '島根県' },
      { word: '平泉', reading: 'ひらいずみ', hint: '岩手県' },
      { word: '小笠原諸島', reading: 'おがさわらしょとう', hint: '東京都' },
      { word: '富士山', reading: 'ふじさん', hint: '山梨・静岡' },
      { word: '富岡製糸場', reading: 'とみおかせいしじょう', hint: '群馬県' },
      { word: '明治日本の産業革命遺産', reading: 'めいじにほんのさんぎょうかくめいいさん', hint: '8県' },
      { word: '国立西洋美術館', reading: 'こくりつせいようびじゅつかん', hint: '東京都' },
      { word: '宗像大社', reading: 'むなかたたいしゃ', hint: '福岡県' },
      { word: '長崎の教会群', reading: 'ながさきのきょうかいぐん', hint: '長崎県' },
      { word: '百舌鳥古市古墳群', reading: 'もずふるいちこふんぐん', hint: '大阪府' },
      { word: '奄美大島', reading: 'あまみおおしま', hint: '鹿児島県' },
      { word: '北海道・北東北の縄文遺跡群', reading: 'ほっかいどう・きたとうほくのじょうもんいせきぐん', hint: '北海道・青森・岩手・秋田' }
    ]
  }
];
